const Burgers = [{
        id: '1',
        name: 'Meat Burger',
        ingredients: 'Mixed Burger',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '2',
        name: 'Cheese Burger',
        ingredients: 'Cheese Burger',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '3',
        name: 'Pepperoni Burger',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '4',
        name: 'Napolitaine Burger',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
    {
        id: '5',
        name: 'Meat Burger',
        ingredients: 'Mixed Burger',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '6',
        name: 'Cheese Burger',
        ingredients: 'Cheese Burger',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '7',
        name: 'Pepperoni Burger',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '8',
        name: 'Napolitaine Burger',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    }, {
        id: '1',
        name: 'Meat Burger',
        ingredients: 'Mixed Burger',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '2',
        name: 'Cheese Burger',
        ingredients: 'Cheese Burger',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '3',
        name: 'Pepperoni Burger',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '4',
        name: 'Napolitaine Burger',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
    {
        id: '5',
        name: 'Meat Burger',
        ingredients: 'Mixed Burger',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '6',
        name: 'Cheese Burger',
        ingredients: 'Cheese Burger',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '7',
        name: 'Pepperoni Burger',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '8',
        name: 'Napolitaine Burger',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
];

export default Burgers;