const foods = [{
        id: '1',
        category: "Pizza",

        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        category: "Pizza",
        id: '2',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        category: "Pizza",
        id: '3',
        name: 'Pepperoni Pizza',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        category: "Pizza",
        id: '4',
        name: 'Napolitaine Pizza',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
    {
        category: "Pizza",
        id: '5',
        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        category: "Pizza",
        id: '6',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        category: "Pizza",
        id: '7',
        name: 'Pepperoni Pizza',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        category: "Pizza",
        id: '8',
        name: 'Napolitaine Pizza',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    }, {
        category: "Pizza",
        id: '9',
        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        category: "Pizza",
        id: '10',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        category: "Pizza",
        id: '11',
        name: 'Pepperoni Pizza',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        category: "Pizza",
        id: '12',
        name: 'Napolitaine Pizza',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
    {
        category: "Pizza",
        id: '13',
        name: 'Meat Pizza',
        ingredients: 'Mixed Pizza',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        category: "Pizza",
        id: '14',
        name: 'Cheese Pizza',
        ingredients: 'Cheese Pizza',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        category: "Pizza",
        id: '15',
        name: 'Pepperoni Pizza',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        category: "Pizza",
        id: '16',
        name: 'Napolitaine Pizza',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
];

export default foods;