const Sandwichs = [{
        id: '1',
        name: 'Meat Sandwich',
        ingredients: 'Mixed Sandwich',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '2',
        name: 'Cheese Sandwich',
        ingredients: 'Cheese Sandwich',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '3',
        name: 'Pepperoni Sandwich',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '4',
        name: 'Napolitaine Sandwich',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
    {
        id: '5',
        name: 'Meat Sandwich',
        ingredients: 'Mixed Sandwich',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '6',
        name: 'Cheese Sandwich',
        ingredients: 'Cheese Sandwich',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '7',
        name: 'Pepperoni Sandwich',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '8',
        name: 'Napolitaine Sandwich',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    }, {
        id: '1',
        name: 'Meat Sandwich',
        ingredients: 'Mixed Sandwich',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '2',
        name: 'Cheese Sandwich',
        ingredients: 'Cheese Sandwich',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '3',
        name: 'Pepperoni Sandwich',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '4',
        name: 'Napolitaine Sandwich',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
    {
        id: '5',
        name: 'Meat Sandwich',
        ingredients: 'Mixed Sandwich',
        price: '12.00',
        image: require('../assets/meatPizza.png'),
    },
    {
        id: '6',
        name: 'Cheese Sandwich',
        ingredients: 'Cheese Sandwich',
        price: '16.00',
        image: require('../assets/cheesePizza.png'),
    },
    {
        id: '7',
        name: 'Pepperoni Sandwich',
        ingredients: 'Fried Chicken',
        price: '18.00',
        image: require('../assets/pepperoniPizza2.png'),
    },
    {
        id: '8',
        name: 'Napolitaine Sandwich',
        ingredients: 'Salmon Meat',
        price: '14.00',
        image: require('../assets/napolitainePizza.png'),
    },
];

export default Sandwichs;